// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgeeeivbmfrwrieyzhel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZWVlaXZibWZyd3JpZXl6aGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTA4NzcsImV4cCI6MjA2MzU2Njg3N30.8e8Cgw1Butps-HY4GJhngLM3FdCOgGJ314ZODPocNgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);